#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from sofar.msg import TrackedShapes
from sofar.msg import TrackedShape
from sofar.msg import adapter
from sofar.msg import obj
from sofar.msg import feature



def callback(data): 
	
	types = ['float32','float32','string','float32[]']
	name = ['pose_3d','pose_2d','shape_tag','c']
	
	elements = adapter()	
	elements.id_mod = 1	
	
	for j in range (0,len(data.tr)):
		o = obj()						
		for i in range(0,len(name)):
			f = feature()
			f.name = name[i]
			f.types = types[i]
			if name[i] == 'pose_3d':
				f.value.append(data.tr[j].x_3d)
				f.value.append(data.tr[j].y_3d)
				f.value.append(data.tr[j].z_3d)
			if name[i] == 'pose_2d':
				f.value.append(data.tr[j].x_2d)
				f.value.append(data.tr[j].y_2d)
			if name[i] == 'shape_tag':
				f.value.append(data.tr[j].shape_tag)
			if name[i] == 'c':
				f.value.append(data.tr[j].shape_tag)
			o.obj.append(f)
		elements.adap.append(o)
	print(elements)
	print( )
	
def listener():    
    rospy.Subscriber('PittChannel', TrackedShapes, callback)    
    rospy.spin()

if __name__ == '__main__':	
	rospy.init_node('adapterPitt', anonymous=True)	
	listener()

