#!/usr/bin/env python

import rospy
from std_msgs.msg import String
from sofar.msg import TrackedShapes
from sofar.msg import TrackedShape

def talker():
    pub = rospy.Publisher('PittChannel', TrackedShapes, queue_size=10)
    rospy.init_node('talkerPitt', anonymous=True)
    rate = rospy.Rate(30) # 10hz
    while not rospy.is_shutdown():        
        
        msg1 = TrackedShape()
        msg2 = TrackedShape()
        
        msgs = TrackedShapes()       
        msg1.x_3d=4.1
        msg1.y_3d=4.2
        msg1.z_3d=4.3
        msg1.x_2d=4.4
        msg1.y_2d=4.5
        msg1.shape_tag = 'quadrato'        
        msg1.c.append(3)
        
        msgs.tr.append(msg1)
               
        msg2.x_3d=5.1
        msg2.y_3d=5.2
        msg2.z_3d=5.3
        msg2.x_2d=5.4
        msg2.y_2d=5.6
        msg2.shape_tag = 'rettangolo'
        msg2.c.append(3)
        msg2.c.append(5)
        
        msgs.tr.append(msg2)   
        
        print(msgs)
        
        pub.publish(msgs)
        rate.sleep()
		     
if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
